/**
 * Next.js configuration for the AutoEdit frontend.
 *
 * Why this configuration exists:
 * 1. Keep the frontend production-ready for local and Docker-based deployment.
 * 2. Support App Router usage in Next.js 14.
 * 3. Provide a convenient reverse-proxy for backend REST endpoints when the
 *    frontend is used as the main user entrypoint.
 * 4. Stay compatible with the existing frontend code:
 *    - frontend/lib/api.ts falls back to relative "/api/v1/..." requests;
 *    - frontend/lib/ws.ts can also use same-origin paths when
 *      NEXT_PUBLIC_API_BASE_URL is not provided.
 *
 * Important integration note:
 * - The current frontend code can work in two modes:
 *   A) direct mode via NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
 *   B) proxied same-origin mode via Next.js rewrites below
 *
 * For WebSocket traffic, the most reliable production setup is still to set
 * NEXT_PUBLIC_API_BASE_URL explicitly to the backend origin. However, the
 * rewrite configuration remains useful for REST requests and local convenience.
 */

/** @type {import("next").NextConfig} */
const nextConfig = {
  /**
   * Enable React strict mode for safer development behavior and better
   * detection of accidental side effects in client components.
   */
  reactStrictMode: true,

  /**
   * Standalone output is useful for containerized deployment because it allows
   * slimmer production images and cleaner packaging of the Next.js server.
   */
  output: "standalone",

  /**
   * The frontend interacts with large video workflows and download endpoints.
   * Disabling the "powered by" header is a small hardening step.
   */
  poweredByHeader: false,

  /**
   * Keep the build tolerant to containerized and CI environments where linting
   * may be executed as a separate step.
   */
  eslint: {
    ignoreDuringBuilds: false,
  },

  /**
   * TypeScript errors should fail production builds because the project is
   * explicitly typed and should remain contract-safe across API/UI layers.
   */
  typescript: {
    ignoreBuildErrors: false,
  },

  /**
   * Expose only safe public runtime variables to the client bundle.
   *
   * Existing frontend code already reads:
   * - process.env.NEXT_PUBLIC_API_BASE_URL
   *
   * We normalize it here so the application has a predictable value in both
   * development and containerized environments.
   */
  env: {
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL || "",
  },

  /**
   * Security-oriented response headers for the Next.js-served frontend.
   *
   * The CSP is intentionally moderate because the application uses:
   * - inline styles generated by Next/font;
   * - blob/data URLs that may appear in browser media handling;
   * - same-origin API communication and optional explicit backend origin.
   *
   * If deployment later introduces a strict reverse proxy, these headers can be
   * refined there as well.
   */
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "X-Frame-Options",
            value: "DENY",
          },
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value:
              "camera=(), microphone=(), geolocation=(), interest-cohort=()",
          },
          {
            key: "Cross-Origin-Opener-Policy",
            value: "same-origin",
          },
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
              "style-src 'self' 'unsafe-inline'",
              "img-src 'self' data: blob:",
              "font-src 'self' data:",
              "media-src 'self' data: blob: http: https:",
              "connect-src 'self' ws: wss: http: https:",
              "frame-ancestors 'none'",
              "base-uri 'self'",
              "form-action 'self'",
            ].join("; "),
          },
        ],
      },
    ];
  },

  /**
   * Reverse-proxy backend HTTP API calls through the frontend origin.
   *
   * This is especially useful when frontend/lib/api.ts uses relative URLs like
   * "/api/v1/..." because NEXT_PUBLIC_API_BASE_URL is empty.
   *
   * Default backend target:
   * - http://backend:8000 in Docker network
   * - can be overridden via INTERNAL_API_BASE_URL
   *
   * Note:
   * - This rewrite is intended for HTTP endpoints.
   * - For WebSocket stability in production, prefer setting
   *   NEXT_PUBLIC_API_BASE_URL directly to the backend address used by clients.
   */
  async rewrites() {
    const backendBaseUrl =
      process.env.INTERNAL_API_BASE_URL ||
      process.env.NEXT_PUBLIC_API_BASE_URL ||
      "http://backend:8000";

    const normalizedBackendBaseUrl = backendBaseUrl.endsWith("/")
      ? backendBaseUrl.slice(0, -1)
      : backendBaseUrl;

    return [
      {
        source: "/api/:path*",
        destination: `${normalizedBackendBaseUrl}/api/:path*`,
      },
    ];
  },
};

module.exports = nextConfig;